// server.js — AEM QA Framework report server + dashboard host.
// Zero npm dependencies: Node core only.
//
// Runs identically on a laptop (`npm start`) and on Railway. Railway gives us a
// long-lived process with a mountable volume, so reports are written to disk and
// genuinely persist — unlike the previous serverless handler, which kept them in
// a per-instance array that evaporated on every cold start.
//
// Endpoints
//   POST /api/report           save an audit report
//   GET  /api/reports          list report summaries (newest first)
//   GET  /api/report-details   fetch one full report by ?id=
//   GET  /health               liveness probe for Railway
// The unprefixed /report, /reports and /report-details are kept as aliases so
// older compiled bookmarklets keep working.

var http = require('http');
var fs   = require('fs');
var path = require('path');
var url  = require('url');

var PORT        = process.env.PORT || 3500;
var PUBLIC      = path.join(__dirname, 'public');
var REPORTS     = process.env.REPORTS_DIR || (process.env.VERCEL ? path.join('/tmp', 'reports') : path.join(__dirname, 'reports'));
var API_TOKEN   = process.env.QA_API_TOKEN || null;
var MAX_REPORTS = parseInt(process.env.MAX_REPORTS, 10) || 500;
var MAX_BODY    = 2 * 1024 * 1024; // 2 MB — audit payloads are ~20–200 KB

try {
  fs.mkdirSync(REPORTS, { recursive: true });
} catch (e) {
  try {
    REPORTS = path.join('/tmp', 'reports');
    fs.mkdirSync(REPORTS, { recursive: true });
  } catch (e2) {
    console.error('Could not create reports directory ' + REPORTS + ': ' + e2.message);
  }
}

var MIME = {
  '.html': 'text/html; charset=utf-8',
  '.css':  'text/css; charset=utf-8',
  '.js':   'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg':  'image/svg+xml',
  '.ico':  'image/x-icon',
  '.png':  'image/png',
  '.txt':  'text/plain; charset=utf-8',
};

// ─── HELPERS ─────────────────────────────────────────────────────────────

function sendJson(res, status, data, extraHeaders) {
  var headers = { 'Content-Type': 'application/json; charset=utf-8' };
  if (extraHeaders) Object.keys(extraHeaders).forEach(function (k) { headers[k] = extraHeaders[k]; });
  res.writeHead(status, headers);
  res.end(JSON.stringify(data));
}

// Writes are cross-origin by nature: the bookmarklet posts from whatever AEM
// origin the author is on. Reads are deliberately NOT given a permissive CORS
// header — reports embed internal author/stage URLs and page content, so only
// the same-origin dashboard should be able to list or open them.
function allowCrossOriginWrite(res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, X-QA-Token');
  res.setHeader('Vary', 'Origin');
}

function authorized(req) {
  if (!API_TOKEN) return true; // no token configured → open (local dev default)
  var supplied = req.headers['x-qa-token'];
  if (!supplied) return false;
  // Length-independent compare; these are short strings so a plain compare is
  // acceptable, but avoid leaking length via early return where cheap.
  return supplied.length === API_TOKEN.length && supplied === API_TOKEN;
}

function readBody(req, limit) {
  return new Promise(function (resolve, reject) {
    var chunks = [];
    var size = 0;
    req.on('data', function (c) {
      size += c.length;
      if (size > limit) {
        reject(new Error('Payload too large'));
        req.destroy();
        return;
      }
      chunks.push(c);
    });
    req.on('end', function () { resolve(Buffer.concat(chunks).toString('utf8')); });
    req.on('error', reject);
  });
}

// Report ids are generated by us, but they arrive back from the client as query
// params, so they are re-validated before ever touching the filesystem.
var ID_PATTERN = /^[A-Za-z0-9._-]+$/;

function reportPath(id) {
  if (!id || !ID_PATTERN.test(id) || id.indexOf('..') !== -1) return null;
  var file = path.join(REPORTS, id.endsWith('.json') ? id : id + '.json');
  // Defence in depth: the resolved path must still sit inside REPORTS.
  if (path.relative(REPORTS, file).startsWith('..')) return null;
  return file;
}

function makeReportId(reportUrl) {
  var slug = String(reportUrl || 'page').replace(/[^a-z0-9]/gi, '-').replace(/-+/g, '-').substring(0, 60);
  var ts = new Date().toISOString().replace(/[:.]/g, '-');
  return slug + '--' + ts;
}

function listReports() {
  var files;
  try {
    files = fs.readdirSync(REPORTS).filter(function (f) { return f.endsWith('.json'); });
  } catch (e) {
    return [];
  }
  return files.map(function (f) {
    try {
      var data = JSON.parse(fs.readFileSync(path.join(REPORTS, f), 'utf8'));
      var meta = data.meta || {};
      return {
        id: f.replace(/\.json$/, ''),
        file: f,
        url: meta.url || 'Unknown',
        // null for quick scans, which have no comparable 0-100. Coercing that
        // to 0 would render a clean quick scan as a catastrophic score.
        score: typeof meta.overallScore === 'number' ? meta.overallScore : null,
        status: meta.status || meta.goNoGo || 'UNKNOWN',
        auditMode: meta.auditMode || 'full',
        blockerCount: typeof meta.p1FailCount === 'number' ? meta.p1FailCount : null,
        auditedAt: meta.auditedAt || '',
        defectsCount: Array.isArray(data.defects) ? data.defects.length : 0
      };
    } catch (e) {
      return null;
    }
  }).filter(Boolean).sort(function (a, b) {
    return String(b.auditedAt).localeCompare(String(a.auditedAt));
  });
}

// Keep the newest MAX_REPORTS on disk. Prevents an unbounded volume from an
// automated audit loop.
function pruneReports() {
  try {
    var all = fs.readdirSync(REPORTS)
      .filter(function (f) { return f.endsWith('.json'); })
      .map(function (f) {
        var p = path.join(REPORTS, f);
        return { f: f, t: fs.statSync(p).mtimeMs, p: p };
      })
      .sort(function (a, b) { return b.t - a.t; });
    all.slice(MAX_REPORTS).forEach(function (entry) {
      try { fs.unlinkSync(entry.p); } catch (e) {}
    });
  } catch (e) {}
}

// ─── STATIC FILES ────────────────────────────────────────────────────────

function serveStatic(pathname, res) {
  // Decode first, then normalise, then verify containment. Skipping any of
  // these is how `/../../etc/passwd` used to escape the public directory.
  var decoded;
  try {
    decoded = decodeURIComponent(pathname);
  } catch (e) {
    res.writeHead(400); return res.end('Bad request');
  }
  if (decoded.indexOf('\0') !== -1) { res.writeHead(400); return res.end('Bad request'); }

  var rel = path.normalize(decoded).replace(/^(\.\.[/\\])+/, '');
  var filePath = path.join(PUBLIC, rel === '/' || rel === '\\' ? 'index.html' : rel);

  if (path.relative(PUBLIC, filePath).startsWith('..')) {
    res.writeHead(403); return res.end('Forbidden');
  }

  fs.stat(filePath, function (err, stat) {
    if (err || !stat.isFile()) { res.writeHead(404); return res.end('Not found'); }
    res.writeHead(200, { 'Content-Type': MIME[path.extname(filePath)] || 'application/octet-stream' });
    fs.createReadStream(filePath).pipe(res);
  });
}

// ─── SERVER ──────────────────────────────────────────────────────────────

var handleRequest = async function (req, res) {
  var parsed = url.parse(req.url, true);
  var pathname = parsed.pathname.replace(/\/+$/, '') || '/';
  var route = pathname.replace(/^\/api/, '') || '/';

  if (pathname === '/health' || route === '/health') {
    return sendJson(res, 200, { ok: true, reports: listReports().length, uptime: process.uptime() });
  }

  // ── POST a report ──────────────────────────────────────────────────────
  if (route === '/report' && (req.method === 'POST' || req.method === 'OPTIONS')) {
    allowCrossOriginWrite(res);
    if (req.method === 'OPTIONS') { res.writeHead(204); return res.end(); }

    if (!authorized(req)) return sendJson(res, 401, { ok: false, error: 'Invalid or missing X-QA-Token' });

    var raw;
    try {
      raw = await readBody(req, MAX_BODY);
    } catch (e) {
      return sendJson(res, 413, { ok: false, error: 'Payload too large (max ' + MAX_BODY + ' bytes)' });
    }

    var data;
    try {
      data = JSON.parse(raw);
    } catch (e) {
      return sendJson(res, 400, { ok: false, error: 'Invalid JSON: ' + e.message });
    }
    if (!data || typeof data !== 'object' || !data.meta) {
      return sendJson(res, 400, { ok: false, error: 'Missing "meta" in report payload' });
    }

    var id = makeReportId(data.meta.url);
    data.id = id;
    var target = reportPath(id);
    if (!target) return sendJson(res, 400, { ok: false, error: 'Could not derive a safe report id' });

    try {
      fs.writeFileSync(target, JSON.stringify(data, null, 2));
    } catch (e) {
      return sendJson(res, 500, { ok: false, error: 'Failed to persist report: ' + e.message });
    }
    pruneReports();
    return sendJson(res, 200, { ok: true, id: id, message: 'Report saved' });
  }

  // ── Compiled bookmarklet payload ───────────────────────────────────────
  // Served from dist/ so the dashboard always hands out the payload built from
  // the current engine, instead of a copy pasted into the page months ago.
  if (req.method === 'GET' && route === '/bookmarklet') {
    var variant = parsed.query.variant === 'local' ? 'LOCAL' : 'HOSTED';
    var mode = parsed.query.mode === 'quick' ? 'QUICK' : 'FULL';
    var payload = path.join(__dirname, 'dist', 'AEM_QA_BOOKMARK_' + variant + '_' + mode + '.txt');
    if (!fs.existsSync(payload)) {
      return sendJson(res, 503, { error: 'Bookmarklet not built yet. Run: npm run build' });
    }
    res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'no-store' });
    return res.end(fs.readFileSync(payload));
  }

  // ── Read endpoints: same-origin only (no CORS header emitted) ───────────
  if (req.method === 'GET' && route === '/reports') {
    if (!authorized(req)) return sendJson(res, 401, { error: 'Invalid or missing X-QA-Token' });
    return sendJson(res, 200, listReports());
  }

  if (req.method === 'GET' && route === '/report-details') {
    if (!authorized(req)) return sendJson(res, 401, { error: 'Invalid or missing X-QA-Token' });
    var wanted = parsed.query.id || parsed.query.file;
    var file = reportPath(wanted);
    // A miss is a 404. It used to fall back to reports[0], which silently
    // showed the operator a different page's audit than the one they clicked.
    if (!file || !fs.existsSync(file)) return sendJson(res, 404, { error: 'Report not found' });
    try {
      return sendJson(res, 200, JSON.parse(fs.readFileSync(file, 'utf8')));
    } catch (e) {
      return sendJson(res, 500, { error: 'Report is unreadable: ' + e.message });
    }
  }

  if (req.method !== 'GET') { res.writeHead(405); return res.end('Method not allowed'); }

  return serveStatic(pathname, res);
};

var server = http.createServer(handleRequest);

if (!process.env.VERCEL) {
  server.listen(PORT, function () {
    console.log('AEM QA server listening on port ' + PORT);
    console.log('  dashboard : http://localhost:' + PORT);
    console.log('  reports   : ' + REPORTS);
    console.log('  auth      : ' + (API_TOKEN ? 'X-QA-Token required' : 'open (set QA_API_TOKEN to require a token)'));
  });
}

module.exports = server;
module.exports.handleRequest = handleRequest;
